### ISSUE TITLE
Missing 'my_matplotlib_style' file

### ISSUE THREAD

**Issue by honeygupta** [Autoencoders-compression-anomaly/AE-Compression-pytorch#1]
Hi, 

The package is missing _my_matplotlib_style_ (matplot custom settings) file. Can you please add it to the repo?

Thanks,
Honey

**Comment by Skelpdar** [comment]
I was in the process of removing all references to that settings file when cleaning up the project.

Some legacy files like that (and a a lot of different examples) can be found in Eric Wulff's original repo: https://github.com/erwulff/lth_thesis_project

In this case, I would suggest just removing the reference to my_matplotlib_style

**Comment by honeygupta** [comment]
Ok. Thanks for the info. Are you planning to modify the files to remove the missing references?
