### ISSUE TITLE
Request to add data files

### ISSUE THREAD

**Issue by honeygupta** [Autoencoders-compression-anomaly/AE-Compression-pytorch#2]
Hi,

Can you please add the data files - .pkl or data frames in the form of CSV or text files to the repo? It would be helpful to reproduce the results and perform further experiments.

Thanks,
Honey

**Comment by Skelpdar** [comment]
I believe that the raw data like this may not be made public. (and also large files are troublesome with git, if one doesn't use git-lfs) 

For the data used in these examples, send me an email and I will personally give them to you somehow. For any more raw data, you would have to ask your supervisor.

**Comment by honeygupta** [comment]
I think the processed files should work for the initial experiments. Can you please share them with me? My email-id is _hn.gpt1@gmail.com_ . I can share an empty gdrive folder in case you have storage constraints.

Thanks,
Honey

**Comment by urania277** [comment]
@Skelpdar could you use CERNBox so that we can set the proper permissions? https://cernbox.cern.ch - you should have 1 TB for yourself (but it will go away once your CERN affiliation expires at the end of the summer)

**Comment by Skelpdar** [comment]
All data is now on CERNBox and as an intermediate, Caterina will give you access to some of the raw and processed data that you need.

**Comment by honeygupta** [comment]
Thanks!
